In [1]:
import pandas as pd

df = pd.read_csv("../datasets/raw/US_Accidents_March23.csv", nrows=100000)
df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,...,False,False,False,False,True,False,Day,Day,Day,Day

In [2]:
# Create a copy 
copy_df = df
copy_df

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,...,False,False,False,False,True,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,A-100002,Source2,3,2016-04-05 15:52:14,2016-04-05 16:52:14,32.731979,-117.111244,NaN,NaN,0.00,...,False,False,False,False,False,False,Day,Day,Day,Day
99996,A-100003,Source2,3,2016-04-05 15:57:10,2016-04-05 16:57:10,33.913029,-118.125389,NaN,NaN,0.00,...,False,False,False,False,False,False,Day,Day,Day,Day
99997,A-100004,Source2,2,2016-04-05 16:02:16,2016-04-05 17:02:16,34.121517,-117.536896,NaN,NaN,0.00,...,False,False,False,False,True,False,Day,Day,Day,Day
99998,A-100005,Source3,2,2016-04-05 16:01:17,2016-04-05 17:01:17,33.995079,-117.361183,NaN,NaN,0.00,...,False,False,False,False,False,False,Day,Day,Day,Day
99999,A-100006,Source2,2,2016-04-05 16:06:41,2016-04-05 17:06:41,34.034119,-118.013443,NaN,NaN,0.00,...,False,False,False,False,False,False,Day,Day,Day,Day

In [3]:
# Eliminate blank spaces at the bigginning and at the end 
copy_df = copy_df.apply(
    lambda col: col.str.strip() 
    if col.dtype == "object" 
        else col
)

In [4]:
print(copy_df.columns)

Index(['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)', 'Description',
       'Street', 'City', 'County', 'State', 'Zipcode', 'Country', 'Timezone',
       'Airport_Code', 'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)',
       'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [5]:
# Eliminate unnecessary columns form the copy
copy_df = copy_df.drop(["End_Lat", "End_Lng"], axis=1)

In [6]:
copy_df = copy_df.drop(
    [
        "ID", "Source", "Description", 
        "Zipcode", "Country", "Timezone",
        "Country", "Timezone", "Airport_Code",
        "Weather_Timestamp", "End_Time"
     ],
    axis=1
)

In [7]:
copy_df = copy_df.drop(
    [
        'Civil_Twilight', 'Nautical_Twilight', 'Astronomical_Twilight',
        'Wind_Chill(F)', 'Pressure(in)', 'Wind_Direction',
        'County', 'Distance(mi)'
    ],
    axis=1
)

In [8]:
# Verify if the dropped columns doesn't exist at copy
print(copy_df.columns)

Index(['Severity', 'Start_Time', 'Start_Lat', 'Start_Lng', 'Street', 'City',
       'State', 'Temperature(F)', 'Humidity(%)', 'Visibility(mi)',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop', 'Sunrise_Sunset'],
      dtype='object')

In [11]:
# convert the date string into date date
copy_df["Start_Time"] = pd.to_datetime(copy_df["Start_Time"], errors="coerce")

# Ahora sí puedes verificar
print("Tipo de dato actual:", copy_df['Start_Time'].dtype)

Tipo de dato actual: datetime64[ns]

In [12]:
copy_df['Hour'] =  copy_df['Start_Time'].dt.hour
copy_df['Month'] = copy_df['Start_Time'].dt.month
copy_df['Weekday'] =  copy_df['Start_Time'].dt.weekday

In [13]:
bool_cols = [
    'Amenity', 'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 
    'Railway', 'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 
    'Traffic_Signal', 'Turning_Loop'
]
existing_bools = [col for col in bool_cols if col in copy_df.columns]
copy_df[existing_bools] = copy_df[existing_bools].astype(int)

In [14]:
copy_df['Sunrise_Sunset'] = copy_df['Sunrise_Sunset'].fillna('Day')
copy_df['Is_Day'] = copy_df['Sunrise_Sunset'].apply(lambda x: 1 if x == 'Day' else 0)

copy_df = copy_df.drop('Sunrise_Sunset', axis=1)

In [16]:
print(copy_df.head())

   Severity          Start_Time  Start_Lat  Start_Lng  \
0         3 2016-02-08 05:46:00  39.865147 -84.058723
1         2 2016-02-08 06:07:59  39.928059 -82.831184
2         2 2016-02-08 06:49:27  39.063148 -84.032608
3         3 2016-02-08 07:23:34  39.747753 -84.205582
4         2 2016-02-08 07:39:07  39.627781 -84.188354

                      Street          City State  Temperature(F)  Humidity(%)  \
0                     I-70 E        Dayton    OH            36.9         91.0
1                   Brice Rd  Reynoldsburg    OH            37.9        100.0
2             State Route 32  Williamsburg    OH            36.0        100.0
3                     I-75 S        Dayton    OH            35.1         96.0
4  Miamisburg Centerville Rd        Dayton    OH            36.0         89.0

   Visibility(mi)  ...  Roundabout  Station Stop  Traffic_Calming  \
0            10.0  ...           0        0    0                0
1            10.0  ...           0        0    0                0
2            10.0  ...           0        0    0                0
3             9.0  ...           0        0    0                0
4             6.0  ...           0        0    0                0

   Traffic_Signal  Turning_Loop  Hour  Month  Weekday  Is_Day
0               0             0     5      2        0       0
1               0             0     6      2        0       0
2               1             0     6      2        0       0
3               0             0     7      2        0       0
4               1             0     7      2        0       1

[5 rows x 30 columns]

In [18]:
copy_df = copy_df.drop("Start_Time", axis=1)
print(copy_df.columns)

Index(['Severity', 'Start_Lat', 'Start_Lng', 'Street', 'City', 'State',
       'Temperature(F)', 'Humidity(%)', 'Visibility(mi)', 'Wind_Speed(mph)',
       'Precipitation(in)', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop', 'Hour',
       'Month', 'Weekday', 'Is_Day'],
      dtype='object')

In [ ]:
print("Verificando columnas antes de guardar:")
print(copy_df.columns)

Verificando columnas antes de guardar:
Index(['Severity', 'Start_Lat', 'Start_Lng', 'Street', 'City', 'State',
       'Temperature(F)', 'Humidity(%)', 'Visibility(mi)', 'Wind_Speed(mph)',
       'Precipitation(in)', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop', 'Hour',
       'Month', 'Weekday', 'Is_Day'],
      dtype='object')

In [25]:
path = "../datasets/processed/accidents_clean.csv"

copy_df.to_csv(path, index=False, header=True)

print("The new cleaned dataset has been saved at dataset/processed/")

The new cleaned dataset has been saved at dataset/processed/